### ISSUE TITLE
Not able to load BAM using pileupjs

### ISSUE THREAD

**Issue by deepaksibar** [hammerlab/pileup.js#406] opened 2016-03-20 19:25 UTC
I am trying to load my BAM file using pileupjs. But BAM is not getting loaded and following error thrown by pileupjs library.

q.js:161 Uncaught Monster request: Won't fetch Infinity bytes from ./data/bam/B907_2__reHeader_Sorted.bam

I am trying with demo code given on hammerlab website and using my BAM file (B907_2__reHeader_Sorted.bam and its index file) instead of demo BAM file.

Please let me know why i am getting this error and how it can be fixed ??

**Comment by armish** [comment] 2016-03-21 14:34
Duplicate of #405. 

@deepaksibar: if you don't mind, let's continue the conversation under #405.

**Closed** 2016-04-07 14:57 UTC
