### ISSUE TITLE
Library not working with Chrome or Safari - ERR_CACHE_OPERATION_NOT_SUPPORTED

### ISSUE THREAD

**Issue by tweep** [hammerlab/pileup.js#412] opened 2016-05-10 22:56 UTC
Hello,

I'm having trouble using your pipeup.js library with Chrome and Safari - I get this exception: 

Failed to load resource: net::ERR_CACHE_OPERATION_NOT_SUPPORTED

I'm using chrome Version 50.0.2661.94 (64-bit) and Safari version 8.08 on Mac os X. 

Jan

**Comment by armish** [comment] 2016-05-11 16:13
Hi Jan,

Thanks for giving pileup.js a try and reporting this issue back to us. I will be more than happy to investigate what might be going wrong here. The error you mentioned is somewhat unspecific and might be due to your working environment, as a quick Google search led me to descriptions of WebKit-related issues rather JS libraries. Also, I am using the same exact versions of the browsers, but wasn't able to reproduce this problem.

Would you mind sending us a screenshot of the full-stack for this error? If this is coming from pileup.js, with the help of the Chrome developer tools, we can trace it down to where it stems from. To do so, please open your Chrome browser and browse to the page you had trouble viewing pileup.js. Then, open the Developer utils using the menu: `View > Developer > Developer Tools`. After switching to the `Console` tab, refresh the page a few times to make sure it is not related to your browser cache. If the error persists, there should be a triangle icon next to the error message that will allow you to see the stack for this particular error. You can take a screenshot of that list of files and send it our way, which will help us better understand what might be going wrong.

In the meantime, can you also provide us with more details? For example, are you having problem with the demo page on our servers or on a custom page you are developing? Do you have some sample code that you can share with us?..

Thanks!
-- Arman

**Comment by tweep** [comment] 2016-05-12 04:36
Hello Arman, 

thank you for your detailed email - I took a fresh new checkout from github and I do not see any errors in Chrome, using the bam files you provide. So the error occurs in our custom code /setup, not if we use your fresh checkout.

When I’m trying to use our setup ( we got tomcat server which has our bam-files linked and can stream the bam/bai files ) we get an error in Safari and Chrome, but not in Firefox (ERR_CACHE_OPERATION_NOT_SUPPORTED). 

I guess we’ve set up something which Chrome does not like and is strict about out - maybe some header thingy.

I’ve attached a couple of screenshots of the error you see in Chrome. 

I got the feeling that it’s related to the byte range request and maybe related to eETags- i came across these sites : 

https://github.com/sharelatex/angular-pdfjs-viewer <https://github.com/sharelatex/angular-pdfjs-viewer>   (bottom of page)  and https://en.wikipedia.org/wiki/HTTP_ETag <https://en.wikipedia.org/wiki/HTTP_ETag> 

Today i realized,that when i zoom OUT of the initially loaded region ( chr17, 7,512,284-7,512,644 ) or choose a different chromosome, chrome is loading the data and displaying it correctly. 

Any hints welcome. 

By the way the IndexChunk loading via passing JSON objects is very fast. I love it!

   Jan

**Comment by armish** [comment] 2016-05-12 20:29
Hey Jan,

Looks like your attachments didn't make it through. You can either put them up on GitHub issue or e-mail me directly at arman@aksoy.org Thanks for these details. Hopefully we can figure out what might be going wrong in your case by looking at those. The worst comes to worst, I might ask for a slice of your bam file so that I can reproduce and try to fix this issue on our end.

Best,
-- Arman

**Comment by armish** [comment] 2016-05-23 22:46
Hi Jan,

Thanks for the detailed information and relating this to ETags! Unfortunately, I don't have an immediate solution to this on the pileup.js side. My understanding from the links you provided is that this is happening because of a weird interplay between the client's range implementation and server's response, but I wasn't able to find a quick workaround for this within the library that is initiating the request.

I am closing this issue for now, but please let me know if you have any suggestions or solutions to this; we can always bring this on the table once more.

**Closed by armish** 2016-05-23 22:46 UTC
